#
#  Makefile for the kernel Sensor device drivers.
#

# Object files in subdirectories
obj-$(CONFIG_ACCEL)		+= accel/
obj-$(CONFIG_OPTICAL)		+= optical/
obj-$(CONFIG_COMPASS)		+= compass/
obj-$(CONFIG_GYRO_MPU3050)	+= gyro-mpu3050/
obj-$(CONFIG_MPU_SENSORS_MPU3050)	+= mpu3050/
obj-$(CONFIG_SENSORS_CORE)	+= core/
