obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_LQ043T1DG01) += panel-sharp-lq043t1dg01.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-NL8048HL11-01B.o
obj-$(CONFIG_PANEL_PICO_DLP) +=  panel-picodlp.o
obj-$(CONFIG_PANEL_TOPPOLY_TDO35S) += panel-toppoly-tdo35s.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_SAMSUNG_LTN121AT) += panel-samsung-ltn121at.o
obj-$(CONFIG_PANEL_SAMSUNG_D10E50T6332) += panel-samsung-D10E50T6332.o cmc623.o
obj-$(CONFIG_PANEL_AMS353) += panel-ams353.o
obj-$(CONFIG_PANEL_LD9040) += panel-ld9040.o
obj-$(CONFIG_PANEL_S6E8AA0) += panel-s6e8aa0.o
obj-$(CONFIG_PANEL_IMGSENSOR_CMC623) += tune_cmc623.o

