

obj-$(CONFIG_SAMSUNG_BATTERY) := samsung_battery.o
samsung_battery-y :=
samsung_battery-y += battery_monitor.o
samsung_battery-y += charger_twl6030.o
samsung_battery-y += fuelgauge_max17043.o

clean:
	@rm -rf *.ko *.mod.* .*.cmd *.o .tmp_versions 	modules.order Module.symvers










