# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_INPUT_EAR_KEY)	+= earkey.o
# SIO Switch Driver
obj-$(CONFIG_SWITCH_SIO)	+= switch_sio.o
obj-$(CONFIG_EAR_MIC_ADC)	+= ear_mic_adc.o

