##
# Copyright (C) 2010-2011, Samsung Electronics, Co., Ltd. All Rights Reserved.
#  Written by System S/W Group, S/W Platform R&D Team,
#  Mobile Communication Division.
##

##
# Project Name : Samsung Private Third-Party Device Drivers
#
# Project Description :
#
# Comments : tabstop = 8, shiftwidth = 8, noexpandtab
##

##
# File Name : Makefile
#
# File Description :
#
# Author : System Platform 2
# Dept : System S/W Group (S/W Platform R&D Team)
# Created Date : 10/Mar/2011
# Version : Baby-Raccoon
##

obj-$(CONFIG_SAMSUNG_BATTERY)	+= battery/
obj-$(CONFIG_FMRADIO)	+= fm_si4709/
obj-$(CONFIG_SAMSUNG_J4FS)	+= j4fs/
obj-$(CONFIG_SAMSUNG_PARAM)	+= param/
obj-$(CONFIG_SAMSUNG_VIBETONZ)	+= vibetonz/

