cmd_drivers/gpu/pvr/pdump.o := /opt/toolchains/arm-2009q3/bin/arm-none-linux-gnueabi-gcc -Wp,-MD,drivers/gpu/pvr/.pdump.o.d  -nostdinc -isystem /opt/toolchains/arm-2009q3/bin/../lib/gcc/arm-none-linux-gnueabi/4.4.1/include -I/home/hanny/kernel/Lucifr/arch/arm/include -Iinclude  -include include/generated/autoconf.h -I/home/hanny/kernel/Lucifr/samsung/include -I/home/hanny/kernel/Lucifr/samsung/rfs_fsr/include -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-omap2/include -Iarch/arm/plat-omap/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -marm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -include arch/arm/plat-omap/include/plat/mux_t1_rev_r07.h -D_SAMSUNG_BOARD_NAME=t1 -Wframe-larger-than=1024 -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DLINUX -D__linux__ -Idrivers/gpu/pvr -DANDROID -DPVR_BUILD_DIR="\"omap_sgx_android\"" -DSGX_DYNAMIC_TIMING_INFO -DSYS_CUSTOM_POWERLOCK_WRAP -DSERVICES4 -DSUPPORT_SRVINIT -DSUPPORT_PERCONTEXT_PB -DTRANSFER_QUEUE -DSYS_USING_INTERRUPTS -DSUPPORT_LINUX_X86_WRITECOMBINE -DSUPPORT_LINUX_X86_PAT -DPVR_SECURE_HANDLES -DPVR_SECURE_FD_EXPORT -DLDM_PLATFORM -DSUPPORT_SGX_HWPERF -DSUPPORT_MEMINFO_IDS -DDISPLAY_CONTROLLER=omaplfb -DSYS_SGX_ACTIVE_POWER_LATENCY_MS=2 -DPVR_BUILD_DATE="" -DSUPPORT_SGX -DCLIENT_DRIVER_DEFAULT_WAIT_RETRIES=50 -DPVR_LINUX_TIMERS_USING_WORKQUEUES -DFLIP_TECHNIQUE_OVERLAY -DPVR_LINUX_USING_WORKQUEUES -DPVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE -DSUPPORT_SGX_NEW_STATUS_VALS -DSGX_EARLYSUSPEND -DPVR_NO_OMAP_TIMER -DSUPPORT_SGX_LOW_LATENCY_SCHEDULING -DPVRSRV_MODNAME="\"pvrsrvkm"\" -Idrivers/gpu/pvr/omap4 -Idrivers/gpu/pvr/sgx -DSGX_CLK_CORE_DIV5 -DSGX540 -DSUPPORT_SGX540 -DSGX_CORE_REV=120 -DPVR_BUILD_TYPE="\"release\"" -DRELEASE -DSUPPORT_ACTIVE_POWER_MANAGEMENT -DSUPPORT_HW_RECOVERY -DPVR_NO_FULL_CACHE_OPS   -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(pdump)"  -D"KBUILD_MODNAME=KBUILD_STR(pvr_common)"  -c -o drivers/gpu/pvr/pdump.o drivers/gpu/pvr/pdump.c

deps_drivers/gpu/pvr/pdump.o := \
  drivers/gpu/pvr/pdump.c \
  arch/arm/plat-omap/include/plat/mux_t1_rev_r07.h \
    $(wildcard include/config/video/mhl/v1.h) \

drivers/gpu/pvr/pdump.o: $(deps_drivers/gpu/pvr/pdump.o)

$(deps_drivers/gpu/pvr/pdump.o):
